#pragma once
#include <iostream>
#include <stack> 
#include <string>
#include <memory> 
#include "macros/macros.h"
#include "controller/AtlController.h"
#include "service/assertion/Assertion.h"
#include "presenter/output/ConsoleOutputWriter.h"
#include "model/TestContainer.h"
#include "model/AllTests.h"
