#pragma once
#include "template.h"
#include "macros/macros.h"
#include "controller/AtlController.h"
#include "service/assertion/Assertion.h"
#include "service/assertion/AssertBuilder.h"
#include "service/assertion/IsEqualTo.h"
#include "presenter/output/ConsoleOutputWriter.h"
#include "testBuilder/TestBuilder.h"